name: Build and Publish Resume
on:
  push:
    branches:
      - main
jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: resume.pdf
      - name: Build deploy folder
        run: |
          mkdir -p deploy
          cp index.html resume.pdf deploy/
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: resume
          directory: deploy
      - name: Purge cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        with:
            cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
            cf_auth: ${{ secrets.CLOUDFLARE_API_TOKEN }}